version: '3.8'

services:
  db:
    image: postgres:15-alpine3.17
    restart: always
    ports:
      - "7777:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: public
    volumes:
      - ./data:/var/lib/postgresql/data